packages:
  - "."
  - "infrastructure"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

minimumReleaseAge: 14400
minimumReleaseAgeExclude:
  - next
  - '@next/*'
  - react
  - react-dom
allowBuilds:
  '@pulumi/command': true
  cpu-features: true
  protobufjs: true
  sharp: true
  ssh2: true
