packages:
  - "."
  - "infrastructure"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

minimumReleaseAge: 14400
minimumReleaseAgeExclude:
  - next
  - '@next/*'
  - react
  - react-dom
